name: CICD Demo

on: 
  push:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "Code Cloned"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: echo "Code Built"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the code
        run: echo "Code Tested"

  deploy:
    needs: [code, build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the code
        run: echo "Code Deployed"
