name: Hello GitHub Actions

on:
  push: 

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: print gretting
        run: echo "Hello from Github Actions!"
