name: Hello GitHub Actions

on:
  push: 

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: print gretting
        run: echo "Hello from Github Actions!"

      - name: Print current date and time
        run: date

      - name: print branch name
        run: 'echo "Branch: ${{ github.ref_name }}"'

      -name: List files
        run: ls -la

      - name: Print runner OS
        run: 'echo "Runner OS: ${{runner.os}}"'

        
