# GOAL: Trigger on pull request

name: PR check

on:
  # pull_request:
  #   branches:
  #     - main

  workflow_dispatch:


jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Print PR branch
        run: 'echo "PR check running for branch: ${{ github.head_ref }}"'