# GOAL: use secrets as environment variables

name: secret as Environment Variable

on:
    workflow_dispatch:

jobs:
    use-secret:
        runs-on: ubuntu-latest

        steps:
            - name: Use secret as environment variable
              env:
                SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
              run: |
                if [ -n "$SECRET_MESSAGE" ]; then
                    echo "Secret is available through environment variable"
                else:
                    echo "secret is not available"
                fi
