# GOAL: workflow that reads and prints secrets from the repository

name: secrets

on:
    workflow_dispatch:

jobs:
    check-secret:
        runs-on: ubuntu-latest

        steps:
            - name: check if secret is set
              run: |
                if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
                    echo "The secret is set: true"
                else
                    echo "The secret is set: false"
                fi

            - name: test secret masking
              run: echo "${{ secrets.MY_SECRET_MESSAGE }}"